// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCKOg3ip8eqVsiLEd1k3rTX_Bzj85B1eI',
    appId: '1:510672685761:web:9ecb63e8b2dbd4eccaa240',
    messagingSenderId: '510672685761',
    projectId: 'inapppurchase-28dfc',
    authDomain: 'inapppurchase-28dfc.firebaseapp.com',
    storageBucket: 'inapppurchase-28dfc.appspot.com',
    measurementId: 'G-5PDJT2LXDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOWJmLWAAGCSLkar-mn2qOb-ebJuIEcFo',
    appId: '1:510672685761:android:19755dead54e95f4caa240',
    messagingSenderId: '510672685761',
    projectId: 'inapppurchase-28dfc',
    storageBucket: 'inapppurchase-28dfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv-v-0BO-RatVDFWHAxOLO8WQgftR9Q14',
    appId: '1:510672685761:ios:b93636b67bef9dd3caa240',
    messagingSenderId: '510672685761',
    projectId: 'inapppurchase-28dfc',
    storageBucket: 'inapppurchase-28dfc.appspot.com',
    iosClientId: '510672685761-cpqul3nj12cbquddun1oqvc45squ2thr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasecore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv-v-0BO-RatVDFWHAxOLO8WQgftR9Q14',
    appId: '1:510672685761:ios:0dfc10f821b4e53acaa240',
    messagingSenderId: '510672685761',
    projectId: 'inapppurchase-28dfc',
    storageBucket: 'inapppurchase-28dfc.appspot.com',
    iosClientId: '510672685761-h8g9pj09jh7hhc5ao86jtkjjqbkimodf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasecore.RunnerTests',
  );
}
